/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.workflow.model;

import java.util.Objects;
import com.finbourne.workflow.model.CorrelationIdMapping;
import com.finbourne.workflow.model.EventTaskFieldMapping;
import com.finbourne.workflow.model.LauncherEventMatchingPattern;
import com.finbourne.workflow.model.LauncherMapping;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.workflow.JSON;

/**
 * A Launcher that starts a run of its Workflow when a matching platform event arrives, and can fill fields and correlation IDs of the root task from that event
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EventLauncherDetails {
  /**
   * Gets or Sets launcherType
   */
  @JsonAdapter(LauncherTypeEnum.Adapter.class)
  public enum LauncherTypeEnum {
    EVENT("Event");

    private String value;

    LauncherTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LauncherTypeEnum fromValue(String value) {
      for (LauncherTypeEnum b : LauncherTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LauncherTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LauncherTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LauncherTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LauncherTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_LAUNCHER_TYPE = "launcherType";
  @SerializedName(SERIALIZED_NAME_LAUNCHER_TYPE)
  private LauncherTypeEnum launcherType;

  public static final String SERIALIZED_NAME_EVENT_MATCHING_PATTERN = "eventMatchingPattern";
  @SerializedName(SERIALIZED_NAME_EVENT_MATCHING_PATTERN)
  private LauncherEventMatchingPattern eventMatchingPattern;

  public static final String SERIALIZED_NAME_MAP_TASK_FIELDS = "mapTaskFields";
  @SerializedName(SERIALIZED_NAME_MAP_TASK_FIELDS)
  private Map<String, EventTaskFieldMapping> mapTaskFields;

  public static final String SERIALIZED_NAME_MAP_CORRELATION_IDS = "mapCorrelationIds";
  @SerializedName(SERIALIZED_NAME_MAP_CORRELATION_IDS)
  private List<CorrelationIdMapping> mapCorrelationIds;

  public static final String SERIALIZED_NAME_RUN_AS_USER_ID = "runAsUserId";
  @SerializedName(SERIALIZED_NAME_RUN_AS_USER_ID)
  private LauncherMapping runAsUserId;

  public static final String SERIALIZED_NAME_SET_TASK_FIELDS = "setTaskFields";
  @SerializedName(SERIALIZED_NAME_SET_TASK_FIELDS)
  private Map<String, Object> setTaskFields;

  public static final String SERIALIZED_NAME_SET_CORRELATION_IDS = "setCorrelationIds";
  @SerializedName(SERIALIZED_NAME_SET_CORRELATION_IDS)
  private List<String> setCorrelationIds;

  public static final String SERIALIZED_NAME_INITIAL_TRIGGER = "initialTrigger";
  @SerializedName(SERIALIZED_NAME_INITIAL_TRIGGER)
  private String initialTrigger;

  public EventLauncherDetails() {
  }

  public EventLauncherDetails launcherType(LauncherTypeEnum launcherType) {
    
    this.launcherType = launcherType;
    return this;
  }

   /**
   * Get launcherType
   * @return launcherType
  **/
  @jakarta.annotation.Nonnull
  public LauncherTypeEnum getLauncherType() {
    return launcherType;
  }


  public void setLauncherType(LauncherTypeEnum launcherType) {
    this.launcherType = launcherType;
  }


  public EventLauncherDetails eventMatchingPattern(LauncherEventMatchingPattern eventMatchingPattern) {
    
    this.eventMatchingPattern = eventMatchingPattern;
    return this;
  }

   /**
   * Get eventMatchingPattern
   * @return eventMatchingPattern
  **/
  @jakarta.annotation.Nonnull
  public LauncherEventMatchingPattern getEventMatchingPattern() {
    return eventMatchingPattern;
  }


  public void setEventMatchingPattern(LauncherEventMatchingPattern eventMatchingPattern) {
    this.eventMatchingPattern = eventMatchingPattern;
  }


  public EventLauncherDetails mapTaskFields(Map<String, EventTaskFieldMapping> mapTaskFields) {
    
    this.mapTaskFields = mapTaskFields;
    return this;
  }

  public EventLauncherDetails putMapTaskFieldsItem(String key, EventTaskFieldMapping mapTaskFieldsItem) {
    if (this.mapTaskFields == null) {
      this.mapTaskFields = new HashMap<>();
    }
    this.mapTaskFields.put(key, mapTaskFieldsItem);
    return this;
  }

   /**
   * Fields of the root task filled from the event, keyed by the field name on the root task definition
   * @return mapTaskFields
  **/
  @jakarta.annotation.Nullable
  public Map<String, EventTaskFieldMapping> getMapTaskFields() {
    return mapTaskFields;
  }


  public void setMapTaskFields(Map<String, EventTaskFieldMapping> mapTaskFields) {
    this.mapTaskFields = mapTaskFields;
  }


  public EventLauncherDetails mapCorrelationIds(List<CorrelationIdMapping> mapCorrelationIds) {
    
    this.mapCorrelationIds = mapCorrelationIds;
    return this;
  }

  public EventLauncherDetails addMapCorrelationIdsItem(CorrelationIdMapping mapCorrelationIdsItem) {
    if (this.mapCorrelationIds == null) {
      this.mapCorrelationIds = new ArrayList<>();
    }
    this.mapCorrelationIds.add(mapCorrelationIdsItem);
    return this;
  }

   /**
   * Correlation IDs of the root task filled from the event
   * @return mapCorrelationIds
  **/
  @jakarta.annotation.Nullable
  public List<CorrelationIdMapping> getMapCorrelationIds() {
    return mapCorrelationIds;
  }


  public void setMapCorrelationIds(List<CorrelationIdMapping> mapCorrelationIds) {
    this.mapCorrelationIds = mapCorrelationIds;
  }


  public EventLauncherDetails runAsUserId(LauncherMapping runAsUserId) {
    
    this.runAsUserId = runAsUserId;
    return this;
  }

   /**
   * Get runAsUserId
   * @return runAsUserId
  **/
  @jakarta.annotation.Nonnull
  public LauncherMapping getRunAsUserId() {
    return runAsUserId;
  }


  public void setRunAsUserId(LauncherMapping runAsUserId) {
    this.runAsUserId = runAsUserId;
  }


  public EventLauncherDetails setTaskFields(Map<String, Object> setTaskFields) {
    
    this.setTaskFields = setTaskFields;
    return this;
  }

  public EventLauncherDetails putSetTaskFieldsItem(String key, Object setTaskFieldsItem) {
    if (this.setTaskFields == null) {
      this.setTaskFields = new HashMap<>();
    }
    this.setTaskFields.put(key, setTaskFieldsItem);
    return this;
  }

   /**
   * Fields of the root task set to a fixed value, keyed by the field name on the root task definition
   * @return setTaskFields
  **/
  @jakarta.annotation.Nullable
  public Map<String, Object> getSetTaskFields() {
    return setTaskFields;
  }


  public void setSetTaskFields(Map<String, Object> setTaskFields) {
    this.setTaskFields = setTaskFields;
  }


  public EventLauncherDetails setCorrelationIds(List<String> setCorrelationIds) {
    
    this.setCorrelationIds = setCorrelationIds;
    return this;
  }

  public EventLauncherDetails addSetCorrelationIdsItem(String setCorrelationIdsItem) {
    if (this.setCorrelationIds == null) {
      this.setCorrelationIds = new ArrayList<>();
    }
    this.setCorrelationIds.add(setCorrelationIdsItem);
    return this;
  }

   /**
   * Correlation IDs put on the root task as given
   * @return setCorrelationIds
  **/
  @jakarta.annotation.Nullable
  public List<String> getSetCorrelationIds() {
    return setCorrelationIds;
  }


  public void setSetCorrelationIds(List<String> setCorrelationIds) {
    this.setCorrelationIds = setCorrelationIds;
  }


  public EventLauncherDetails initialTrigger(String initialTrigger) {
    
    this.initialTrigger = initialTrigger;
    return this;
  }

   /**
   * The trigger given to the root task once it is made and all of its fields are filled. When it is left out the root task is left in its initial state
   * @return initialTrigger
  **/
  @jakarta.annotation.Nullable
  public String getInitialTrigger() {
    return initialTrigger;
  }


  public void setInitialTrigger(String initialTrigger) {
    this.initialTrigger = initialTrigger;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventLauncherDetails eventLauncherDetails = (EventLauncherDetails) o;
    return Objects.equals(this.launcherType, eventLauncherDetails.launcherType) &&
        Objects.equals(this.eventMatchingPattern, eventLauncherDetails.eventMatchingPattern) &&
        Objects.equals(this.mapTaskFields, eventLauncherDetails.mapTaskFields) &&
        Objects.equals(this.mapCorrelationIds, eventLauncherDetails.mapCorrelationIds) &&
        Objects.equals(this.runAsUserId, eventLauncherDetails.runAsUserId) &&
        Objects.equals(this.setTaskFields, eventLauncherDetails.setTaskFields) &&
        Objects.equals(this.setCorrelationIds, eventLauncherDetails.setCorrelationIds) &&
        Objects.equals(this.initialTrigger, eventLauncherDetails.initialTrigger);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(launcherType, eventMatchingPattern, mapTaskFields, mapCorrelationIds, runAsUserId, setTaskFields, setCorrelationIds, initialTrigger);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventLauncherDetails {\n");
    sb.append("    launcherType: ").append(toIndentedString(launcherType)).append("\n");
    sb.append("    eventMatchingPattern: ").append(toIndentedString(eventMatchingPattern)).append("\n");
    sb.append("    mapTaskFields: ").append(toIndentedString(mapTaskFields)).append("\n");
    sb.append("    mapCorrelationIds: ").append(toIndentedString(mapCorrelationIds)).append("\n");
    sb.append("    runAsUserId: ").append(toIndentedString(runAsUserId)).append("\n");
    sb.append("    setTaskFields: ").append(toIndentedString(setTaskFields)).append("\n");
    sb.append("    setCorrelationIds: ").append(toIndentedString(setCorrelationIds)).append("\n");
    sb.append("    initialTrigger: ").append(toIndentedString(initialTrigger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("launcherType");
    openapiFields.add("eventMatchingPattern");
    openapiFields.add("mapTaskFields");
    openapiFields.add("mapCorrelationIds");
    openapiFields.add("runAsUserId");
    openapiFields.add("setTaskFields");
    openapiFields.add("setCorrelationIds");
    openapiFields.add("initialTrigger");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("launcherType");
    openapiRequiredFields.add("eventMatchingPattern");
    openapiRequiredFields.add("runAsUserId");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to EventLauncherDetails
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EventLauncherDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EventLauncherDetails is not found in the empty JSON string", EventLauncherDetails.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EventLauncherDetails.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("launcherType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `launcherType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("launcherType").toString()));
      }
      // validate the required field `eventMatchingPattern`
      LauncherEventMatchingPattern.validateJsonElement(jsonObj.get("eventMatchingPattern"));
      if (jsonObj.get("mapCorrelationIds") != null && !jsonObj.get("mapCorrelationIds").isJsonNull()) {
        JsonArray jsonArraymapCorrelationIds = jsonObj.getAsJsonArray("mapCorrelationIds");
        if (jsonArraymapCorrelationIds != null) {
          // ensure the json data is an array
          if (!jsonObj.get("mapCorrelationIds").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `mapCorrelationIds` to be an array in the JSON string but got `%s`", jsonObj.get("mapCorrelationIds").toString()));
          }

          // validate the optional field `mapCorrelationIds` (array)
          for (int i = 0; i < jsonArraymapCorrelationIds.size(); i++) {
            CorrelationIdMapping.validateJsonElement(jsonArraymapCorrelationIds.get(i));
          };
        }
      }
      // validate the required field `runAsUserId`
      LauncherMapping.validateJsonElement(jsonObj.get("runAsUserId"));
      // ensure the optional json data is an array if present
      if (jsonObj.get("setCorrelationIds") != null && !jsonObj.get("setCorrelationIds").isJsonNull() && !jsonObj.get("setCorrelationIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `setCorrelationIds` to be an array in the JSON string but got `%s`", jsonObj.get("setCorrelationIds").toString()));
      }
      if ((jsonObj.get("initialTrigger") != null && !jsonObj.get("initialTrigger").isJsonNull()) && !jsonObj.get("initialTrigger").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `initialTrigger` to be a primitive type in the JSON string but got `%s`", jsonObj.get("initialTrigger").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventLauncherDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventLauncherDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventLauncherDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventLauncherDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<EventLauncherDetails>() {
           @Override
           public void write(JsonWriter out, EventLauncherDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EventLauncherDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EventLauncherDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EventLauncherDetails
  * @throws IOException if the JSON string is invalid with respect to EventLauncherDetails
  */
  public static EventLauncherDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventLauncherDetails.class);
  }

 /**
  * Convert an instance of EventLauncherDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
