/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.workflow.model;

import java.util.Objects;
import com.finbourne.workflow.model.CalendarContext;
import com.finbourne.workflow.model.CorrelationIdMapping;
import com.finbourne.workflow.model.EventLauncherDetailsResponse;
import com.finbourne.workflow.model.LauncherEventMatchingPattern;
import com.finbourne.workflow.model.LauncherMapping;
import com.finbourne.workflow.model.LauncherSchedule;
import com.finbourne.workflow.model.ScheduleLauncherDetailsResponse;
import com.finbourne.workflow.model.ScheduleTaskFieldMapping;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.finbourne.workflow.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LauncherDetailsResponse extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(LauncherDetailsResponse.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!LauncherDetailsResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'LauncherDetailsResponse' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<EventLauncherDetailsResponse> adapterEventLauncherDetailsResponse = gson.getDelegateAdapter(this, TypeToken.get(EventLauncherDetailsResponse.class));
            final TypeAdapter<ScheduleLauncherDetailsResponse> adapterScheduleLauncherDetailsResponse = gson.getDelegateAdapter(this, TypeToken.get(ScheduleLauncherDetailsResponse.class));

            return (TypeAdapter<T>) new TypeAdapter<LauncherDetailsResponse>() {
                @Override
                public void write(JsonWriter out, LauncherDetailsResponse value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `EventLauncherDetailsResponse`
                    if (value.getActualInstance() instanceof EventLauncherDetailsResponse) {
                      JsonElement element = adapterEventLauncherDetailsResponse.toJsonTree((EventLauncherDetailsResponse)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    // check if the actual instance is of the type `ScheduleLauncherDetailsResponse`
                    if (value.getActualInstance() instanceof ScheduleLauncherDetailsResponse) {
                      JsonElement element = adapterScheduleLauncherDetailsResponse.toJsonTree((ScheduleLauncherDetailsResponse)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: EventLauncherDetailsResponse, ScheduleLauncherDetailsResponse");
                }

                @Override
                public LauncherDetailsResponse read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize EventLauncherDetailsResponse
                    try {
                      // validate the JSON object to see if any exception is thrown
                      EventLauncherDetailsResponse.validateJsonElement(jsonElement);
                      actualAdapter = adapterEventLauncherDetailsResponse;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'EventLauncherDetailsResponse'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for EventLauncherDetailsResponse failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'EventLauncherDetailsResponse'", e);
                    }
                    // deserialize ScheduleLauncherDetailsResponse
                    try {
                      // validate the JSON object to see if any exception is thrown
                      ScheduleLauncherDetailsResponse.validateJsonElement(jsonElement);
                      actualAdapter = adapterScheduleLauncherDetailsResponse;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'ScheduleLauncherDetailsResponse'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for ScheduleLauncherDetailsResponse failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'ScheduleLauncherDetailsResponse'", e);
                    }

                    if (match == 1) {
                        LauncherDetailsResponse ret = new LauncherDetailsResponse();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for LauncherDetailsResponse: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public LauncherDetailsResponse() {
        super("oneOf", Boolean.FALSE);
    }

    public LauncherDetailsResponse(EventLauncherDetailsResponse o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public LauncherDetailsResponse(ScheduleLauncherDetailsResponse o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("EventLauncherDetailsResponse", EventLauncherDetailsResponse.class);
        schemas.put("ScheduleLauncherDetailsResponse", ScheduleLauncherDetailsResponse.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return LauncherDetailsResponse.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * EventLauncherDetailsResponse, ScheduleLauncherDetailsResponse
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof EventLauncherDetailsResponse) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof ScheduleLauncherDetailsResponse) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be EventLauncherDetailsResponse, ScheduleLauncherDetailsResponse");
    }

    /**
     * Get the actual instance, which can be the following:
     * EventLauncherDetailsResponse, ScheduleLauncherDetailsResponse
     *
     * @return The actual instance (EventLauncherDetailsResponse, ScheduleLauncherDetailsResponse)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `EventLauncherDetailsResponse`. If the actual instance is not `EventLauncherDetailsResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `EventLauncherDetailsResponse`
     * @throws ClassCastException if the instance is not `EventLauncherDetailsResponse`
     */
    public EventLauncherDetailsResponse getEventLauncherDetailsResponse() throws ClassCastException {
        return (EventLauncherDetailsResponse)super.getActualInstance();
    }
    /**
     * Get the actual instance of `ScheduleLauncherDetailsResponse`. If the actual instance is not `ScheduleLauncherDetailsResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ScheduleLauncherDetailsResponse`
     * @throws ClassCastException if the instance is not `ScheduleLauncherDetailsResponse`
     */
    public ScheduleLauncherDetailsResponse getScheduleLauncherDetailsResponse() throws ClassCastException {
        return (ScheduleLauncherDetailsResponse)super.getActualInstance();
    }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to LauncherDetailsResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with EventLauncherDetailsResponse
    try {
      EventLauncherDetailsResponse.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for EventLauncherDetailsResponse failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with ScheduleLauncherDetailsResponse
    try {
      ScheduleLauncherDetailsResponse.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for ScheduleLauncherDetailsResponse failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for LauncherDetailsResponse with oneOf schemas: EventLauncherDetailsResponse, ScheduleLauncherDetailsResponse. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
    }
  }

 /**
  * Create an instance of LauncherDetailsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LauncherDetailsResponse
  * @throws IOException if the JSON string is invalid with respect to LauncherDetailsResponse
  */
  public static LauncherDetailsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LauncherDetailsResponse.class);
  }

 /**
  * Convert an instance of LauncherDetailsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

