/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.workflow.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.workflow.JSON;

/**
 * Information about which states the field can be edited in
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ReadOnlyStates {
  public static final String SERIALIZED_NAME_STATE_TYPE = "stateType";
  @SerializedName(SERIALIZED_NAME_STATE_TYPE)
  private String stateType;

  public static final String SERIALIZED_NAME_SELECTED_STATES = "selectedStates";
  @SerializedName(SERIALIZED_NAME_SELECTED_STATES)
  private List<String> selectedStates;

  public ReadOnlyStates() {
  }

  public ReadOnlyStates stateType(String stateType) {
    
    this.stateType = stateType;
    return this;
  }

   /**
   * The State Type (e.g. InitialState, AllStates, TerminalState, SelectedStates)
   * @return stateType
  **/
  @jakarta.annotation.Nonnull
  public String getStateType() {
    return stateType;
  }


  public void setStateType(String stateType) {
    this.stateType = stateType;
  }


  public ReadOnlyStates selectedStates(List<String> selectedStates) {
    
    this.selectedStates = selectedStates;
    return this;
  }

  public ReadOnlyStates addSelectedStatesItem(String selectedStatesItem) {
    if (this.selectedStates == null) {
      this.selectedStates = new ArrayList<>();
    }
    this.selectedStates.add(selectedStatesItem);
    return this;
  }

   /**
   * Named states for which the field will be readonly - This field can only be populated if StateType &#x3D; SelectedStates
   * @return selectedStates
  **/
  @jakarta.annotation.Nullable
  public List<String> getSelectedStates() {
    return selectedStates;
  }


  public void setSelectedStates(List<String> selectedStates) {
    this.selectedStates = selectedStates;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadOnlyStates readOnlyStates = (ReadOnlyStates) o;
    return Objects.equals(this.stateType, readOnlyStates.stateType) &&
        Objects.equals(this.selectedStates, readOnlyStates.selectedStates);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(stateType, selectedStates);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadOnlyStates {\n");
    sb.append("    stateType: ").append(toIndentedString(stateType)).append("\n");
    sb.append("    selectedStates: ").append(toIndentedString(selectedStates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("stateType");
    openapiFields.add("selectedStates");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("stateType");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ReadOnlyStates
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReadOnlyStates.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReadOnlyStates is not found in the empty JSON string", ReadOnlyStates.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReadOnlyStates.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("stateType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stateType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stateType").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("selectedStates") != null && !jsonObj.get("selectedStates").isJsonNull() && !jsonObj.get("selectedStates").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `selectedStates` to be an array in the JSON string but got `%s`", jsonObj.get("selectedStates").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReadOnlyStates.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReadOnlyStates' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReadOnlyStates> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReadOnlyStates.class));

       return (TypeAdapter<T>) new TypeAdapter<ReadOnlyStates>() {
           @Override
           public void write(JsonWriter out, ReadOnlyStates value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReadOnlyStates read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReadOnlyStates given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReadOnlyStates
  * @throws IOException if the JSON string is invalid with respect to ReadOnlyStates
  */
  public static ReadOnlyStates fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReadOnlyStates.class);
  }

 /**
  * Convert an instance of ReadOnlyStates to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
