/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.workflow.model;

import java.util.Objects;
import com.finbourne.workflow.model.CalendarReference;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.workflow.JSON;

/**
 * Context for a Schedule Matching Pattern
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ScheduleMatchingPatternContext {
  public static final String SERIALIZED_NAME_TIME_ZONE = "timeZone";
  @SerializedName(SERIALIZED_NAME_TIME_ZONE)
  private String timeZone;

  public static final String SERIALIZED_NAME_HOLIDAY_CALENDARS = "holidayCalendars";
  @SerializedName(SERIALIZED_NAME_HOLIDAY_CALENDARS)
  private List<CalendarReference> holidayCalendars;

  public ScheduleMatchingPatternContext() {
  }

  public ScheduleMatchingPatternContext timeZone(String timeZone) {
    
    this.timeZone = timeZone;
    return this;
  }

   /**
   * The time zone to use
   * @return timeZone
  **/
  @jakarta.annotation.Nonnull
  public String getTimeZone() {
    return timeZone;
  }


  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }


  public ScheduleMatchingPatternContext holidayCalendars(List<CalendarReference> holidayCalendars) {
    
    this.holidayCalendars = holidayCalendars;
    return this;
  }

  public ScheduleMatchingPatternContext addHolidayCalendarsItem(CalendarReference holidayCalendarsItem) {
    if (this.holidayCalendars == null) {
      this.holidayCalendars = new ArrayList<>();
    }
    this.holidayCalendars.add(holidayCalendarsItem);
    return this;
  }

   /**
   * References to any Holiday Calendars to use
   * @return holidayCalendars
  **/
  @jakarta.annotation.Nullable
  public List<CalendarReference> getHolidayCalendars() {
    return holidayCalendars;
  }


  public void setHolidayCalendars(List<CalendarReference> holidayCalendars) {
    this.holidayCalendars = holidayCalendars;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleMatchingPatternContext scheduleMatchingPatternContext = (ScheduleMatchingPatternContext) o;
    return Objects.equals(this.timeZone, scheduleMatchingPatternContext.timeZone) &&
        Objects.equals(this.holidayCalendars, scheduleMatchingPatternContext.holidayCalendars);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeZone, holidayCalendars);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleMatchingPatternContext {\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    holidayCalendars: ").append(toIndentedString(holidayCalendars)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("timeZone");
    openapiFields.add("holidayCalendars");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("timeZone");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ScheduleMatchingPatternContext
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScheduleMatchingPatternContext.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ScheduleMatchingPatternContext is not found in the empty JSON string", ScheduleMatchingPatternContext.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ScheduleMatchingPatternContext.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("timeZone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timeZone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeZone").toString()));
      }
      if (jsonObj.get("holidayCalendars") != null && !jsonObj.get("holidayCalendars").isJsonNull()) {
        JsonArray jsonArrayholidayCalendars = jsonObj.getAsJsonArray("holidayCalendars");
        if (jsonArrayholidayCalendars != null) {
          // ensure the json data is an array
          if (!jsonObj.get("holidayCalendars").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `holidayCalendars` to be an array in the JSON string but got `%s`", jsonObj.get("holidayCalendars").toString()));
          }

          // validate the optional field `holidayCalendars` (array)
          for (int i = 0; i < jsonArrayholidayCalendars.size(); i++) {
            CalendarReference.validateJsonElement(jsonArrayholidayCalendars.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScheduleMatchingPatternContext.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScheduleMatchingPatternContext' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScheduleMatchingPatternContext> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScheduleMatchingPatternContext.class));

       return (TypeAdapter<T>) new TypeAdapter<ScheduleMatchingPatternContext>() {
           @Override
           public void write(JsonWriter out, ScheduleMatchingPatternContext value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScheduleMatchingPatternContext read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ScheduleMatchingPatternContext given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ScheduleMatchingPatternContext
  * @throws IOException if the JSON string is invalid with respect to ScheduleMatchingPatternContext
  */
  public static ScheduleMatchingPatternContext fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScheduleMatchingPatternContext.class);
  }

 /**
  * Convert an instance of ScheduleMatchingPatternContext to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
