/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.workflow.model;

import java.util.Objects;
import com.finbourne.workflow.model.ResourceId;
import com.finbourne.workflow.model.Stack;
import com.finbourne.workflow.model.TaskDefinitionVersion;
import com.finbourne.workflow.model.TaskInstanceField;
import com.finbourne.workflow.model.TaskSummary;
import com.finbourne.workflow.model.VersionInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.workflow.JSON;

/**
 * Defines a Task created based on a Task Definition
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Task {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_TASK_DEFINITION_ID = "taskDefinitionId";
  @SerializedName(SERIALIZED_NAME_TASK_DEFINITION_ID)
  private ResourceId taskDefinitionId;

  public static final String SERIALIZED_NAME_TASK_DEFINITION_VERSION = "taskDefinitionVersion";
  @SerializedName(SERIALIZED_NAME_TASK_DEFINITION_VERSION)
  private TaskDefinitionVersion taskDefinitionVersion;

  public static final String SERIALIZED_NAME_TASK_DEFINITION_DISPLAY_NAME = "taskDefinitionDisplayName";
  @SerializedName(SERIALIZED_NAME_TASK_DEFINITION_DISPLAY_NAME)
  private String taskDefinitionDisplayName;

  public static final String SERIALIZED_NAME_WORKFLOW_ID = "workflowId";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_ID)
  private ResourceId workflowId;

  public static final String SERIALIZED_NAME_WORKFLOW_DISPLAY_NAME = "workflowDisplayName";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_DISPLAY_NAME)
  private String workflowDisplayName;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_ULTIMATE_PARENT_TASK = "ultimateParentTask";
  @SerializedName(SERIALIZED_NAME_ULTIMATE_PARENT_TASK)
  private TaskSummary ultimateParentTask;

  public static final String SERIALIZED_NAME_PARENT_TASK = "parentTask";
  @SerializedName(SERIALIZED_NAME_PARENT_TASK)
  private TaskSummary parentTask;

  public static final String SERIALIZED_NAME_CHILD_TASKS = "childTasks";
  @SerializedName(SERIALIZED_NAME_CHILD_TASKS)
  private List<TaskSummary> childTasks;

  public static final String SERIALIZED_NAME_CORRELATION_IDS = "correlationIds";
  @SerializedName(SERIALIZED_NAME_CORRELATION_IDS)
  private List<String> correlationIds;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private VersionInfo version;

  public static final String SERIALIZED_NAME_TERMINAL_STATE = "terminalState";
  @SerializedName(SERIALIZED_NAME_TERMINAL_STATE)
  private Boolean terminalState;

  public static final String SERIALIZED_NAME_AS_AT_LAST_TRANSITION = "asAtLastTransition";
  @SerializedName(SERIALIZED_NAME_AS_AT_LAST_TRANSITION)
  private OffsetDateTime asAtLastTransition;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<TaskInstanceField> fields;

  public static final String SERIALIZED_NAME_STACKING_KEY = "stackingKey";
  @SerializedName(SERIALIZED_NAME_STACKING_KEY)
  private String stackingKey;

  public static final String SERIALIZED_NAME_STACK = "stack";
  @SerializedName(SERIALIZED_NAME_STACK)
  private Stack stack;

  public static final String SERIALIZED_NAME_ACTION_LOG_ID_CREATED = "actionLogIdCreated";
  @SerializedName(SERIALIZED_NAME_ACTION_LOG_ID_CREATED)
  private UUID actionLogIdCreated;

  public static final String SERIALIZED_NAME_ACTION_LOG_ID_MODIFIED = "actionLogIdModified";
  @SerializedName(SERIALIZED_NAME_ACTION_LOG_ID_MODIFIED)
  private UUID actionLogIdModified;

  public static final String SERIALIZED_NAME_ACTION_LOG_ID_SUBMITTED = "actionLogIdSubmitted";
  @SerializedName(SERIALIZED_NAME_ACTION_LOG_ID_SUBMITTED)
  private UUID actionLogIdSubmitted;

  public static final String SERIALIZED_NAME_HIERARCHICAL_POSITION = "hierarchicalPosition";
  @SerializedName(SERIALIZED_NAME_HIERARCHICAL_POSITION)
  private String hierarchicalPosition;

  public static final String SERIALIZED_NAME_COMPLETION_STATUS = "completionStatus";
  @SerializedName(SERIALIZED_NAME_COMPLETION_STATUS)
  private String completionStatus;

  public static final String SERIALIZED_NAME_OPEN_DURATION = "openDuration";
  @SerializedName(SERIALIZED_NAME_OPEN_DURATION)
  private Long openDuration;

  public static final String SERIALIZED_NAME_OPEN_DURATION_SINCE_LAST_UPDATE = "openDurationSinceLastUpdate";
  @SerializedName(SERIALIZED_NAME_OPEN_DURATION_SINCE_LAST_UPDATE)
  private Long openDurationSinceLastUpdate;

  public static final String SERIALIZED_NAME_OPEN_DURATION_SINCE_LAST_TRANSITION = "openDurationSinceLastTransition";
  @SerializedName(SERIALIZED_NAME_OPEN_DURATION_SINCE_LAST_TRANSITION)
  private Long openDurationSinceLastTransition;

  public Task() {
  }

  public Task id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * The unique id for this Task
   * @return id
  **/
  @jakarta.annotation.Nonnull
  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public Task taskDefinitionId(ResourceId taskDefinitionId) {
    
    this.taskDefinitionId = taskDefinitionId;
    return this;
  }

   /**
   * Get taskDefinitionId
   * @return taskDefinitionId
  **/
  @jakarta.annotation.Nonnull
  public ResourceId getTaskDefinitionId() {
    return taskDefinitionId;
  }


  public void setTaskDefinitionId(ResourceId taskDefinitionId) {
    this.taskDefinitionId = taskDefinitionId;
  }


  public Task taskDefinitionVersion(TaskDefinitionVersion taskDefinitionVersion) {
    
    this.taskDefinitionVersion = taskDefinitionVersion;
    return this;
  }

   /**
   * Get taskDefinitionVersion
   * @return taskDefinitionVersion
  **/
  @jakarta.annotation.Nonnull
  public TaskDefinitionVersion getTaskDefinitionVersion() {
    return taskDefinitionVersion;
  }


  public void setTaskDefinitionVersion(TaskDefinitionVersion taskDefinitionVersion) {
    this.taskDefinitionVersion = taskDefinitionVersion;
  }


  public Task taskDefinitionDisplayName(String taskDefinitionDisplayName) {
    
    this.taskDefinitionDisplayName = taskDefinitionDisplayName;
    return this;
  }

   /**
   * The display name of the Task Definition used by this Task
   * @return taskDefinitionDisplayName
  **/
  @jakarta.annotation.Nonnull
  public String getTaskDefinitionDisplayName() {
    return taskDefinitionDisplayName;
  }


  public void setTaskDefinitionDisplayName(String taskDefinitionDisplayName) {
    this.taskDefinitionDisplayName = taskDefinitionDisplayName;
  }


  public Task workflowId(ResourceId workflowId) {
    
    this.workflowId = workflowId;
    return this;
  }

   /**
   * Get workflowId
   * @return workflowId
  **/
  @jakarta.annotation.Nullable
  public ResourceId getWorkflowId() {
    return workflowId;
  }


  public void setWorkflowId(ResourceId workflowId) {
    this.workflowId = workflowId;
  }


  public Task workflowDisplayName(String workflowDisplayName) {
    
    this.workflowDisplayName = workflowDisplayName;
    return this;
  }

   /**
   * The display name of the Workflow that this Task is a member of, if any
   * @return workflowDisplayName
  **/
  @jakarta.annotation.Nullable
  public String getWorkflowDisplayName() {
    return workflowDisplayName;
  }


  public void setWorkflowDisplayName(String workflowDisplayName) {
    this.workflowDisplayName = workflowDisplayName;
  }


  public Task state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * Current State
   * @return state
  **/
  @jakarta.annotation.Nonnull
  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public Task ultimateParentTask(TaskSummary ultimateParentTask) {
    
    this.ultimateParentTask = ultimateParentTask;
    return this;
  }

   /**
   * Get ultimateParentTask
   * @return ultimateParentTask
  **/
  @jakarta.annotation.Nonnull
  public TaskSummary getUltimateParentTask() {
    return ultimateParentTask;
  }


  public void setUltimateParentTask(TaskSummary ultimateParentTask) {
    this.ultimateParentTask = ultimateParentTask;
  }


  public Task parentTask(TaskSummary parentTask) {
    
    this.parentTask = parentTask;
    return this;
  }

   /**
   * Get parentTask
   * @return parentTask
  **/
  @jakarta.annotation.Nullable
  public TaskSummary getParentTask() {
    return parentTask;
  }


  public void setParentTask(TaskSummary parentTask) {
    this.parentTask = parentTask;
  }


  public Task childTasks(List<TaskSummary> childTasks) {
    
    this.childTasks = childTasks;
    return this;
  }

  public Task addChildTasksItem(TaskSummary childTasksItem) {
    if (this.childTasks == null) {
      this.childTasks = new ArrayList<>();
    }
    this.childTasks.add(childTasksItem);
    return this;
  }

   /**
   * This Task&#39;s child tasks
   * @return childTasks
  **/
  @jakarta.annotation.Nullable
  public List<TaskSummary> getChildTasks() {
    return childTasks;
  }


  public void setChildTasks(List<TaskSummary> childTasks) {
    this.childTasks = childTasks;
  }


  public Task correlationIds(List<String> correlationIds) {
    
    this.correlationIds = correlationIds;
    return this;
  }

  public Task addCorrelationIdsItem(String correlationIdsItem) {
    if (this.correlationIds == null) {
      this.correlationIds = new ArrayList<>();
    }
    this.correlationIds.add(correlationIdsItem);
    return this;
  }

   /**
   * User-provided ID used to link entities and tasks
   * @return correlationIds
  **/
  @jakarta.annotation.Nullable
  public List<String> getCorrelationIds() {
    return correlationIds;
  }


  public void setCorrelationIds(List<String> correlationIds) {
    this.correlationIds = correlationIds;
  }


  public Task version(VersionInfo version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @jakarta.annotation.Nullable
  public VersionInfo getVersion() {
    return version;
  }


  public void setVersion(VersionInfo version) {
    this.version = version;
  }


  public Task terminalState(Boolean terminalState) {
    
    this.terminalState = terminalState;
    return this;
  }

   /**
   * True if no onward transitions are possible
   * @return terminalState
  **/
  @jakarta.annotation.Nonnull
  public Boolean getTerminalState() {
    return terminalState;
  }


  public void setTerminalState(Boolean terminalState) {
    this.terminalState = terminalState;
  }


  public Task asAtLastTransition(OffsetDateTime asAtLastTransition) {
    
    this.asAtLastTransition = asAtLastTransition;
    return this;
  }

   /**
   * Last Transition timestamp
   * @return asAtLastTransition
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getAsAtLastTransition() {
    return asAtLastTransition;
  }


  public void setAsAtLastTransition(OffsetDateTime asAtLastTransition) {
    this.asAtLastTransition = asAtLastTransition;
  }


  public Task fields(List<TaskInstanceField> fields) {
    
    this.fields = fields;
    return this;
  }

  public Task addFieldsItem(TaskInstanceField fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Fields and their latest values - should correspond with the Task Definition field schema
   * @return fields
  **/
  @jakarta.annotation.Nullable
  public List<TaskInstanceField> getFields() {
    return fields;
  }


  public void setFields(List<TaskInstanceField> fields) {
    this.fields = fields;
  }


  public Task stackingKey(String stackingKey) {
    
    this.stackingKey = stackingKey;
    return this;
  }

   /**
   * The key used to determine which stack to add the Task to
   * @return stackingKey
  **/
  @jakarta.annotation.Nullable
  public String getStackingKey() {
    return stackingKey;
  }


  public void setStackingKey(String stackingKey) {
    this.stackingKey = stackingKey;
  }


  public Task stack(Stack stack) {
    
    this.stack = stack;
    return this;
  }

   /**
   * Get stack
   * @return stack
  **/
  @jakarta.annotation.Nullable
  public Stack getStack() {
    return stack;
  }


  public void setStack(Stack stack) {
    this.stack = stack;
  }


  public Task actionLogIdCreated(UUID actionLogIdCreated) {
    
    this.actionLogIdCreated = actionLogIdCreated;
    return this;
  }

   /**
   * The Id of the Action that created this Task
   * @return actionLogIdCreated
  **/
  @jakarta.annotation.Nullable
  public UUID getActionLogIdCreated() {
    return actionLogIdCreated;
  }


  public void setActionLogIdCreated(UUID actionLogIdCreated) {
    this.actionLogIdCreated = actionLogIdCreated;
  }


  public Task actionLogIdModified(UUID actionLogIdModified) {
    
    this.actionLogIdModified = actionLogIdModified;
    return this;
  }

   /**
   * The Id of the Action that last modified this Task
   * @return actionLogIdModified
  **/
  @jakarta.annotation.Nullable
  public UUID getActionLogIdModified() {
    return actionLogIdModified;
  }


  public void setActionLogIdModified(UUID actionLogIdModified) {
    this.actionLogIdModified = actionLogIdModified;
  }


  public Task actionLogIdSubmitted(UUID actionLogIdSubmitted) {
    
    this.actionLogIdSubmitted = actionLogIdSubmitted;
    return this;
  }

   /**
   * The Id of the last Action submitted by this Task
   * @return actionLogIdSubmitted
  **/
  @jakarta.annotation.Nullable
  public UUID getActionLogIdSubmitted() {
    return actionLogIdSubmitted;
  }


  public void setActionLogIdSubmitted(UUID actionLogIdSubmitted) {
    this.actionLogIdSubmitted = actionLogIdSubmitted;
  }


  public Task hierarchicalPosition(String hierarchicalPosition) {
    
    this.hierarchicalPosition = hierarchicalPosition;
    return this;
  }

   /**
   * The hierarchical position of this Task: UltimateParent, IntermediateParent, Child, or Standalone
   * @return hierarchicalPosition
  **/
  @jakarta.annotation.Nullable
  public String getHierarchicalPosition() {
    return hierarchicalPosition;
  }


  public void setHierarchicalPosition(String hierarchicalPosition) {
    this.hierarchicalPosition = hierarchicalPosition;
  }


  public Task completionStatus(String completionStatus) {
    
    this.completionStatus = completionStatus;
    return this;
  }

   /**
   * The completion status of this Task: NotStarted, InProgress, or Completed
   * @return completionStatus
  **/
  @jakarta.annotation.Nullable
  public String getCompletionStatus() {
    return completionStatus;
  }


  public void setCompletionStatus(String completionStatus) {
    this.completionStatus = completionStatus;
  }


  public Task openDuration(Long openDuration) {
    
    this.openDuration = openDuration;
    return this;
  }

   /**
   * Duration in seconds since the Task was created. If the Task is Completed, this is the duration from creation to the last transition.
   * @return openDuration
  **/
  @jakarta.annotation.Nullable
  public Long getOpenDuration() {
    return openDuration;
  }


  public void setOpenDuration(Long openDuration) {
    this.openDuration = openDuration;
  }


  public Task openDurationSinceLastUpdate(Long openDurationSinceLastUpdate) {
    
    this.openDurationSinceLastUpdate = openDurationSinceLastUpdate;
    return this;
  }

   /**
   * Duration in seconds since the Task was last updated. 0 if the Task is Completed.
   * @return openDurationSinceLastUpdate
  **/
  @jakarta.annotation.Nullable
  public Long getOpenDurationSinceLastUpdate() {
    return openDurationSinceLastUpdate;
  }


  public void setOpenDurationSinceLastUpdate(Long openDurationSinceLastUpdate) {
    this.openDurationSinceLastUpdate = openDurationSinceLastUpdate;
  }


  public Task openDurationSinceLastTransition(Long openDurationSinceLastTransition) {
    
    this.openDurationSinceLastTransition = openDurationSinceLastTransition;
    return this;
  }

   /**
   * Duration in seconds since the Task last transitioned. 0 if the Task is Completed.
   * @return openDurationSinceLastTransition
  **/
  @jakarta.annotation.Nullable
  public Long getOpenDurationSinceLastTransition() {
    return openDurationSinceLastTransition;
  }


  public void setOpenDurationSinceLastTransition(Long openDurationSinceLastTransition) {
    this.openDurationSinceLastTransition = openDurationSinceLastTransition;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Task task = (Task) o;
    return Objects.equals(this.id, task.id) &&
        Objects.equals(this.taskDefinitionId, task.taskDefinitionId) &&
        Objects.equals(this.taskDefinitionVersion, task.taskDefinitionVersion) &&
        Objects.equals(this.taskDefinitionDisplayName, task.taskDefinitionDisplayName) &&
        Objects.equals(this.workflowId, task.workflowId) &&
        Objects.equals(this.workflowDisplayName, task.workflowDisplayName) &&
        Objects.equals(this.state, task.state) &&
        Objects.equals(this.ultimateParentTask, task.ultimateParentTask) &&
        Objects.equals(this.parentTask, task.parentTask) &&
        Objects.equals(this.childTasks, task.childTasks) &&
        Objects.equals(this.correlationIds, task.correlationIds) &&
        Objects.equals(this.version, task.version) &&
        Objects.equals(this.terminalState, task.terminalState) &&
        Objects.equals(this.asAtLastTransition, task.asAtLastTransition) &&
        Objects.equals(this.fields, task.fields) &&
        Objects.equals(this.stackingKey, task.stackingKey) &&
        Objects.equals(this.stack, task.stack) &&
        Objects.equals(this.actionLogIdCreated, task.actionLogIdCreated) &&
        Objects.equals(this.actionLogIdModified, task.actionLogIdModified) &&
        Objects.equals(this.actionLogIdSubmitted, task.actionLogIdSubmitted) &&
        Objects.equals(this.hierarchicalPosition, task.hierarchicalPosition) &&
        Objects.equals(this.completionStatus, task.completionStatus) &&
        Objects.equals(this.openDuration, task.openDuration) &&
        Objects.equals(this.openDurationSinceLastUpdate, task.openDurationSinceLastUpdate) &&
        Objects.equals(this.openDurationSinceLastTransition, task.openDurationSinceLastTransition);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, taskDefinitionId, taskDefinitionVersion, taskDefinitionDisplayName, workflowId, workflowDisplayName, state, ultimateParentTask, parentTask, childTasks, correlationIds, version, terminalState, asAtLastTransition, fields, stackingKey, stack, actionLogIdCreated, actionLogIdModified, actionLogIdSubmitted, hierarchicalPosition, completionStatus, openDuration, openDurationSinceLastUpdate, openDurationSinceLastTransition);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Task {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    taskDefinitionId: ").append(toIndentedString(taskDefinitionId)).append("\n");
    sb.append("    taskDefinitionVersion: ").append(toIndentedString(taskDefinitionVersion)).append("\n");
    sb.append("    taskDefinitionDisplayName: ").append(toIndentedString(taskDefinitionDisplayName)).append("\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    workflowDisplayName: ").append(toIndentedString(workflowDisplayName)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    ultimateParentTask: ").append(toIndentedString(ultimateParentTask)).append("\n");
    sb.append("    parentTask: ").append(toIndentedString(parentTask)).append("\n");
    sb.append("    childTasks: ").append(toIndentedString(childTasks)).append("\n");
    sb.append("    correlationIds: ").append(toIndentedString(correlationIds)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    terminalState: ").append(toIndentedString(terminalState)).append("\n");
    sb.append("    asAtLastTransition: ").append(toIndentedString(asAtLastTransition)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    stackingKey: ").append(toIndentedString(stackingKey)).append("\n");
    sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
    sb.append("    actionLogIdCreated: ").append(toIndentedString(actionLogIdCreated)).append("\n");
    sb.append("    actionLogIdModified: ").append(toIndentedString(actionLogIdModified)).append("\n");
    sb.append("    actionLogIdSubmitted: ").append(toIndentedString(actionLogIdSubmitted)).append("\n");
    sb.append("    hierarchicalPosition: ").append(toIndentedString(hierarchicalPosition)).append("\n");
    sb.append("    completionStatus: ").append(toIndentedString(completionStatus)).append("\n");
    sb.append("    openDuration: ").append(toIndentedString(openDuration)).append("\n");
    sb.append("    openDurationSinceLastUpdate: ").append(toIndentedString(openDurationSinceLastUpdate)).append("\n");
    sb.append("    openDurationSinceLastTransition: ").append(toIndentedString(openDurationSinceLastTransition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("taskDefinitionId");
    openapiFields.add("taskDefinitionVersion");
    openapiFields.add("taskDefinitionDisplayName");
    openapiFields.add("workflowId");
    openapiFields.add("workflowDisplayName");
    openapiFields.add("state");
    openapiFields.add("ultimateParentTask");
    openapiFields.add("parentTask");
    openapiFields.add("childTasks");
    openapiFields.add("correlationIds");
    openapiFields.add("version");
    openapiFields.add("terminalState");
    openapiFields.add("asAtLastTransition");
    openapiFields.add("fields");
    openapiFields.add("stackingKey");
    openapiFields.add("stack");
    openapiFields.add("actionLogIdCreated");
    openapiFields.add("actionLogIdModified");
    openapiFields.add("actionLogIdSubmitted");
    openapiFields.add("hierarchicalPosition");
    openapiFields.add("completionStatus");
    openapiFields.add("openDuration");
    openapiFields.add("openDurationSinceLastUpdate");
    openapiFields.add("openDurationSinceLastTransition");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("taskDefinitionId");
    openapiRequiredFields.add("taskDefinitionVersion");
    openapiRequiredFields.add("taskDefinitionDisplayName");
    openapiRequiredFields.add("state");
    openapiRequiredFields.add("ultimateParentTask");
    openapiRequiredFields.add("terminalState");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Task
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Task.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Task is not found in the empty JSON string", Task.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Task.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the required field `taskDefinitionId`
      ResourceId.validateJsonElement(jsonObj.get("taskDefinitionId"));
      // validate the required field `taskDefinitionVersion`
      TaskDefinitionVersion.validateJsonElement(jsonObj.get("taskDefinitionVersion"));
      if (!jsonObj.get("taskDefinitionDisplayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `taskDefinitionDisplayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taskDefinitionDisplayName").toString()));
      }
      // validate the optional field `workflowId`
      if (jsonObj.get("workflowId") != null && !jsonObj.get("workflowId").isJsonNull()) {
        ResourceId.validateJsonElement(jsonObj.get("workflowId"));
      }
      if ((jsonObj.get("workflowDisplayName") != null && !jsonObj.get("workflowDisplayName").isJsonNull()) && !jsonObj.get("workflowDisplayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `workflowDisplayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workflowDisplayName").toString()));
      }
      if (!jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      // validate the required field `ultimateParentTask`
      TaskSummary.validateJsonElement(jsonObj.get("ultimateParentTask"));
      // validate the optional field `parentTask`
      if (jsonObj.get("parentTask") != null && !jsonObj.get("parentTask").isJsonNull()) {
        TaskSummary.validateJsonElement(jsonObj.get("parentTask"));
      }
      if (jsonObj.get("childTasks") != null && !jsonObj.get("childTasks").isJsonNull()) {
        JsonArray jsonArraychildTasks = jsonObj.getAsJsonArray("childTasks");
        if (jsonArraychildTasks != null) {
          // ensure the json data is an array
          if (!jsonObj.get("childTasks").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `childTasks` to be an array in the JSON string but got `%s`", jsonObj.get("childTasks").toString()));
          }

          // validate the optional field `childTasks` (array)
          for (int i = 0; i < jsonArraychildTasks.size(); i++) {
            TaskSummary.validateJsonElement(jsonArraychildTasks.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("correlationIds") != null && !jsonObj.get("correlationIds").isJsonNull() && !jsonObj.get("correlationIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `correlationIds` to be an array in the JSON string but got `%s`", jsonObj.get("correlationIds").toString()));
      }
      // validate the optional field `version`
      if (jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) {
        VersionInfo.validateJsonElement(jsonObj.get("version"));
      }
      if (jsonObj.get("fields") != null && !jsonObj.get("fields").isJsonNull()) {
        JsonArray jsonArrayfields = jsonObj.getAsJsonArray("fields");
        if (jsonArrayfields != null) {
          // ensure the json data is an array
          if (!jsonObj.get("fields").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `fields` to be an array in the JSON string but got `%s`", jsonObj.get("fields").toString()));
          }

          // validate the optional field `fields` (array)
          for (int i = 0; i < jsonArrayfields.size(); i++) {
            TaskInstanceField.validateJsonElement(jsonArrayfields.get(i));
          };
        }
      }
      if ((jsonObj.get("stackingKey") != null && !jsonObj.get("stackingKey").isJsonNull()) && !jsonObj.get("stackingKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stackingKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stackingKey").toString()));
      }
      // validate the optional field `stack`
      if (jsonObj.get("stack") != null && !jsonObj.get("stack").isJsonNull()) {
        Stack.validateJsonElement(jsonObj.get("stack"));
      }
      if ((jsonObj.get("actionLogIdCreated") != null && !jsonObj.get("actionLogIdCreated").isJsonNull()) && !jsonObj.get("actionLogIdCreated").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `actionLogIdCreated` to be a primitive type in the JSON string but got `%s`", jsonObj.get("actionLogIdCreated").toString()));
      }
      if ((jsonObj.get("actionLogIdModified") != null && !jsonObj.get("actionLogIdModified").isJsonNull()) && !jsonObj.get("actionLogIdModified").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `actionLogIdModified` to be a primitive type in the JSON string but got `%s`", jsonObj.get("actionLogIdModified").toString()));
      }
      if ((jsonObj.get("actionLogIdSubmitted") != null && !jsonObj.get("actionLogIdSubmitted").isJsonNull()) && !jsonObj.get("actionLogIdSubmitted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `actionLogIdSubmitted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("actionLogIdSubmitted").toString()));
      }
      if ((jsonObj.get("hierarchicalPosition") != null && !jsonObj.get("hierarchicalPosition").isJsonNull()) && !jsonObj.get("hierarchicalPosition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hierarchicalPosition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hierarchicalPosition").toString()));
      }
      if ((jsonObj.get("completionStatus") != null && !jsonObj.get("completionStatus").isJsonNull()) && !jsonObj.get("completionStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `completionStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("completionStatus").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Task.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Task' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Task> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Task.class));

       return (TypeAdapter<T>) new TypeAdapter<Task>() {
           @Override
           public void write(JsonWriter out, Task value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Task read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Task given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Task
  * @throws IOException if the JSON string is invalid with respect to Task
  */
  public static Task fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Task.class);
  }

 /**
  * Convert an instance of Task to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
