/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.workflow.model;

import java.util.Objects;
import com.finbourne.workflow.model.PerpetualProperty;
import com.finbourne.workflow.model.ResourceId;
import com.finbourne.workflow.model.VersionInfo;
import com.finbourne.workflow.model.WorkflowStructure;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.workflow.JSON;

/**
 * A Workflow, including its structure
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WorkflowWithStructureResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private ResourceId id;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private VersionInfo version;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ROOT_TASK_DEFINITION_ID = "rootTaskDefinitionId";
  @SerializedName(SERIALIZED_NAME_ROOT_TASK_DEFINITION_ID)
  private ResourceId rootTaskDefinitionId;

  public static final String SERIALIZED_NAME_WORKFLOW_STRUCTURE = "workflowStructure";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_STRUCTURE)
  private WorkflowStructure workflowStructure;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Map<String, PerpetualProperty> properties;

  public WorkflowWithStructureResponse() {
  }

  public WorkflowWithStructureResponse id(ResourceId id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nonnull
  public ResourceId getId() {
    return id;
  }


  public void setId(ResourceId id) {
    this.id = id;
  }


  public WorkflowWithStructureResponse version(VersionInfo version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @jakarta.annotation.Nullable
  public VersionInfo getVersion() {
    return version;
  }


  public void setVersion(VersionInfo version) {
    this.version = version;
  }


  public WorkflowWithStructureResponse displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * Human readable name
   * @return displayName
  **/
  @jakarta.annotation.Nonnull
  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public WorkflowWithStructureResponse description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Human readable description
   * @return description
  **/
  @jakarta.annotation.Nullable
  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public WorkflowWithStructureResponse rootTaskDefinitionId(ResourceId rootTaskDefinitionId) {
    
    this.rootTaskDefinitionId = rootTaskDefinitionId;
    return this;
  }

   /**
   * Get rootTaskDefinitionId
   * @return rootTaskDefinitionId
  **/
  @jakarta.annotation.Nonnull
  public ResourceId getRootTaskDefinitionId() {
    return rootTaskDefinitionId;
  }


  public void setRootTaskDefinitionId(ResourceId rootTaskDefinitionId) {
    this.rootTaskDefinitionId = rootTaskDefinitionId;
  }


  public WorkflowWithStructureResponse workflowStructure(WorkflowStructure workflowStructure) {
    
    this.workflowStructure = workflowStructure;
    return this;
  }

   /**
   * Get workflowStructure
   * @return workflowStructure
  **/
  @jakarta.annotation.Nonnull
  public WorkflowStructure getWorkflowStructure() {
    return workflowStructure;
  }


  public void setWorkflowStructure(WorkflowStructure workflowStructure) {
    this.workflowStructure = workflowStructure;
  }


  public WorkflowWithStructureResponse properties(Map<String, PerpetualProperty> properties) {
    
    this.properties = properties;
    return this;
  }

  public WorkflowWithStructureResponse putPropertiesItem(String key, PerpetualProperty propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * The properties of the Workflow, keyed by property key
   * @return properties
  **/
  @jakarta.annotation.Nullable
  public Map<String, PerpetualProperty> getProperties() {
    return properties;
  }


  public void setProperties(Map<String, PerpetualProperty> properties) {
    this.properties = properties;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowWithStructureResponse workflowWithStructureResponse = (WorkflowWithStructureResponse) o;
    return Objects.equals(this.id, workflowWithStructureResponse.id) &&
        Objects.equals(this.version, workflowWithStructureResponse.version) &&
        Objects.equals(this.displayName, workflowWithStructureResponse.displayName) &&
        Objects.equals(this.description, workflowWithStructureResponse.description) &&
        Objects.equals(this.rootTaskDefinitionId, workflowWithStructureResponse.rootTaskDefinitionId) &&
        Objects.equals(this.workflowStructure, workflowWithStructureResponse.workflowStructure) &&
        Objects.equals(this.properties, workflowWithStructureResponse.properties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, version, displayName, description, rootTaskDefinitionId, workflowStructure, properties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowWithStructureResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    rootTaskDefinitionId: ").append(toIndentedString(rootTaskDefinitionId)).append("\n");
    sb.append("    workflowStructure: ").append(toIndentedString(workflowStructure)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("version");
    openapiFields.add("displayName");
    openapiFields.add("description");
    openapiFields.add("rootTaskDefinitionId");
    openapiFields.add("workflowStructure");
    openapiFields.add("properties");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("displayName");
    openapiRequiredFields.add("rootTaskDefinitionId");
    openapiRequiredFields.add("workflowStructure");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WorkflowWithStructureResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WorkflowWithStructureResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WorkflowWithStructureResponse is not found in the empty JSON string", WorkflowWithStructureResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WorkflowWithStructureResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `id`
      ResourceId.validateJsonElement(jsonObj.get("id"));
      // validate the optional field `version`
      if (jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) {
        VersionInfo.validateJsonElement(jsonObj.get("version"));
      }
      if (!jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // validate the required field `rootTaskDefinitionId`
      ResourceId.validateJsonElement(jsonObj.get("rootTaskDefinitionId"));
      // validate the required field `workflowStructure`
      WorkflowStructure.validateJsonElement(jsonObj.get("workflowStructure"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WorkflowWithStructureResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WorkflowWithStructureResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WorkflowWithStructureResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WorkflowWithStructureResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<WorkflowWithStructureResponse>() {
           @Override
           public void write(JsonWriter out, WorkflowWithStructureResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WorkflowWithStructureResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WorkflowWithStructureResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WorkflowWithStructureResponse
  * @throws IOException if the JSON string is invalid with respect to WorkflowWithStructureResponse
  */
  public static WorkflowWithStructureResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WorkflowWithStructureResponse.class);
  }

 /**
  * Convert an instance of WorkflowWithStructureResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
