/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.workflow.model;

import java.util.Objects;
import com.finbourne.workflow.model.TaskDefinition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.workflow.JSON;

/**
 * The nodes of a Workflow structure graph — the Task Definitions involved
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WorkflowStructureNodes {
  public static final String SERIALIZED_NAME_TASK_DEFINITIONS = "taskDefinitions";
  @SerializedName(SERIALIZED_NAME_TASK_DEFINITIONS)
  private List<TaskDefinition> taskDefinitions;

  public WorkflowStructureNodes() {
  }

  public WorkflowStructureNodes taskDefinitions(List<TaskDefinition> taskDefinitions) {
    
    this.taskDefinitions = taskDefinitions;
    return this;
  }

  public WorkflowStructureNodes addTaskDefinitionsItem(TaskDefinition taskDefinitionsItem) {
    if (this.taskDefinitions == null) {
      this.taskDefinitions = new ArrayList<>();
    }
    this.taskDefinitions.add(taskDefinitionsItem);
    return this;
  }

   /**
   * The Task Definitions that make up the nodes of this Workflow
   * @return taskDefinitions
  **/
  @jakarta.annotation.Nullable
  public List<TaskDefinition> getTaskDefinitions() {
    return taskDefinitions;
  }


  public void setTaskDefinitions(List<TaskDefinition> taskDefinitions) {
    this.taskDefinitions = taskDefinitions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowStructureNodes workflowStructureNodes = (WorkflowStructureNodes) o;
    return Objects.equals(this.taskDefinitions, workflowStructureNodes.taskDefinitions);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskDefinitions);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowStructureNodes {\n");
    sb.append("    taskDefinitions: ").append(toIndentedString(taskDefinitions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("taskDefinitions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WorkflowStructureNodes
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WorkflowStructureNodes.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WorkflowStructureNodes is not found in the empty JSON string", WorkflowStructureNodes.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("taskDefinitions") != null && !jsonObj.get("taskDefinitions").isJsonNull()) {
        JsonArray jsonArraytaskDefinitions = jsonObj.getAsJsonArray("taskDefinitions");
        if (jsonArraytaskDefinitions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("taskDefinitions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `taskDefinitions` to be an array in the JSON string but got `%s`", jsonObj.get("taskDefinitions").toString()));
          }

          // validate the optional field `taskDefinitions` (array)
          for (int i = 0; i < jsonArraytaskDefinitions.size(); i++) {
            TaskDefinition.validateJsonElement(jsonArraytaskDefinitions.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WorkflowStructureNodes.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WorkflowStructureNodes' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WorkflowStructureNodes> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WorkflowStructureNodes.class));

       return (TypeAdapter<T>) new TypeAdapter<WorkflowStructureNodes>() {
           @Override
           public void write(JsonWriter out, WorkflowStructureNodes value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WorkflowStructureNodes read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WorkflowStructureNodes given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WorkflowStructureNodes
  * @throws IOException if the JSON string is invalid with respect to WorkflowStructureNodes
  */
  public static WorkflowStructureNodes fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WorkflowStructureNodes.class);
  }

 /**
  * Convert an instance of WorkflowStructureNodes to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
