/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.workflow.model;

import java.util.Objects;
import com.finbourne.workflow.model.WorkflowStructureEdges;
import com.finbourne.workflow.model.WorkflowStructureNodes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.workflow.JSON;

/**
 * Describes the structure of a Workflow as a graph of its Task Definitions and its Launchers
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WorkflowStructure {
  public static final String SERIALIZED_NAME_NODES = "nodes";
  @SerializedName(SERIALIZED_NAME_NODES)
  private WorkflowStructureNodes nodes;

  public static final String SERIALIZED_NAME_EDGES = "edges";
  @SerializedName(SERIALIZED_NAME_EDGES)
  private WorkflowStructureEdges edges;

  public static final String SERIALIZED_NAME_LAUNCHERS_TRUNCATED = "launchersTruncated";
  @SerializedName(SERIALIZED_NAME_LAUNCHERS_TRUNCATED)
  private Boolean launchersTruncated;

  public WorkflowStructure() {
  }

  public WorkflowStructure nodes(WorkflowStructureNodes nodes) {
    
    this.nodes = nodes;
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  @jakarta.annotation.Nullable
  public WorkflowStructureNodes getNodes() {
    return nodes;
  }


  public void setNodes(WorkflowStructureNodes nodes) {
    this.nodes = nodes;
  }


  public WorkflowStructure edges(WorkflowStructureEdges edges) {
    
    this.edges = edges;
    return this;
  }

   /**
   * Get edges
   * @return edges
  **/
  @jakarta.annotation.Nullable
  public WorkflowStructureEdges getEdges() {
    return edges;
  }


  public void setEdges(WorkflowStructureEdges edges) {
    this.edges = edges;
  }


  public WorkflowStructure launchersTruncated(Boolean launchersTruncated) {
    
    this.launchersTruncated = launchersTruncated;
    return this;
  }

   /**
   * True when the Workflow has more Launchers than were returned inline in nodes.launchers. Call ListLaunchers for the full set
   * @return launchersTruncated
  **/
  @jakarta.annotation.Nullable
  public Boolean getLaunchersTruncated() {
    return launchersTruncated;
  }


  public void setLaunchersTruncated(Boolean launchersTruncated) {
    this.launchersTruncated = launchersTruncated;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowStructure workflowStructure = (WorkflowStructure) o;
    return Objects.equals(this.nodes, workflowStructure.nodes) &&
        Objects.equals(this.edges, workflowStructure.edges) &&
        Objects.equals(this.launchersTruncated, workflowStructure.launchersTruncated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodes, edges, launchersTruncated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowStructure {\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    edges: ").append(toIndentedString(edges)).append("\n");
    sb.append("    launchersTruncated: ").append(toIndentedString(launchersTruncated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nodes");
    openapiFields.add("edges");
    openapiFields.add("launchersTruncated");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WorkflowStructure
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WorkflowStructure.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WorkflowStructure is not found in the empty JSON string", WorkflowStructure.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `nodes`
      if (jsonObj.get("nodes") != null && !jsonObj.get("nodes").isJsonNull()) {
        WorkflowStructureNodes.validateJsonElement(jsonObj.get("nodes"));
      }
      // validate the optional field `edges`
      if (jsonObj.get("edges") != null && !jsonObj.get("edges").isJsonNull()) {
        WorkflowStructureEdges.validateJsonElement(jsonObj.get("edges"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WorkflowStructure.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WorkflowStructure' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WorkflowStructure> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WorkflowStructure.class));

       return (TypeAdapter<T>) new TypeAdapter<WorkflowStructure>() {
           @Override
           public void write(JsonWriter out, WorkflowStructure value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WorkflowStructure read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WorkflowStructure given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WorkflowStructure
  * @throws IOException if the JSON string is invalid with respect to WorkflowStructure
  */
  public static WorkflowStructure fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WorkflowStructure.class);
  }

 /**
  * Convert an instance of WorkflowStructure to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
